### PR TITLE
Excluded certain MRNs in each script #151

### PR DESCRIPTION
**Pull request by lvarnedoe**
also accounted for years 9999 and days 99

### CODE REVIEW

**Comment by lvarnedoe** [comment]
I have to do the drug exposure script still. I did these while that one got merged so this change wouldn't conflict with the other change I had made to it.

**Comment by lvarnedoe** [comment]
Never mind about the MRNs being excluded in drug exposure. Looks like that was done.

**Review by isangil — CHANGES_REQUESTED** [review]
This is fenomenal, thanks!  Can I ask you a small tweak?
at cnext-observation... change 0s by ''.

		,0 AS OBSERVATION_SOURCE_CONCEPT_ID
        ,0 AS UNIT_SOURCE_VALUE

**Comment by lvarnedoe** [comment]
Of course. I’ll get that done momentarily.

**Review by isangil — APPROVED** [review]

**Pull request merged**
