### PR TITLE
Changed SOURCE__PK to TUMOR.UK #130

### PR DESCRIPTION
**Pull request by lvarnedoe**
Made changes to script so that no dups will be returned. Basing off of Tumor uk, instead of Tumor fk1, which by definition could introduce and does introduce dups.

### CODE REVIEW

**Comment by lvarnedoe** [comment]
That was Mark's doing. I can reach out to him to ask, but I think he said in this morning's meeting that he was pulling the max to get the addr for the patient listed with their most recent tumor. It's the addr in the tumor table.
I left it but removed the select top 1 subquery around it since I am pulling tumor uk as the source_id, I want the addr associated with the tumor. It's the 1st date of diagnosis, but, you are right. Wherever this data is getting dumped will probably not be expecting a date. I can change the date to a string. How about that?

**Comment by isangil** [comment]
yeah, im pretty sure that is wrong.

**Comment by lvarnedoe** [comment]
I'll make it a string. Just a sec.

**Comment by lvarnedoe** [comment]
good catch.

**Comment by isangil** [comment]
I still think it is preferable to put a unique ID there.  the PK for the location -- but since it goes to the LDS and not OMOP, maybe that nuance is taken care of downstream. Here is the definition for Location_ID: 

`The unique key given to a unique Location. | Each instance of a Location in the source data should be assigned this unique key.`

**Comment by isangil** [comment]
I get it is difficult, since the cnext db model is so simplistic, and abuses the parent PKs.  im opened to suggestions, and will approve something that at the very least is almost unique. there is nothing unique about a date.

**Comment by lvarnedoe** [comment]
Yeah, date of diagnosis is not unique. I could put the tumor.uk there. That's the unique key on the table the addr is coming from - makes more sense to me. That's what I'll do. It's what makes the record unique.

**Comment by isangil** [comment]
yeah, that looks better.  the might still be some spurious nulls squawking through, but we can handle those later.

**Pull request merged**
